SPARKVSR_BF16_MODEL_NAME = "SparkVSR-bf16"
SPARKVSR_FP8_SCALED_MODEL_NAME = "SparkVSR-fp8-scaled"
SPARKVSR_INT8_CONVROT_MODEL_NAME = "SparkVSR-int8-convrot"
SPARKVSR_INT8_CONVROT_CACHE_NAME = f"{SPARKVSR_INT8_CONVROT_MODEL_NAME}.safetensors"
